image: ghcr.io/lichess-org/lila-gitpod:main

tasks:
  - name: lila
    command: |
      gp sync-await setup
      cd /workspace/lila
      sbt bloopInstall
      gp sync-done lila-sbt
      bloop compile lila
      bloop run lila -m play.core.server.ProdServerStart
  - name: lila-ws
    command: |
      gp sync-await lila-sbt
      cd /workspace/lila-ws
      sbt compile
      sbt -Dconfig.file=/workspace/lila-ws-gitpod-application.conf run
  - name: setup
    command: |
      gp open /workspace/lila-gitpod/gitpod/Welcome.md
      sudo service nginx restart
      cd /workspace
      git clone https://github.com/lichess-org/lila.git
      git clone https://github.com/lichess-org/lila-ws.git
      git clone https://github.com/lichess-org/lila-db-seed.git
      git clone https://github.com/lichess-org/fishnet.git --recursive
      git clone https://github.com/lichess-org/lila-fishnet.git
      git clone https://github.com/lichess-org/pgn-viewer.git
      ## Create config for lila
      cp /workspace/lila/conf/application.conf.default /workspace/lila/conf/application.conf
      tee -a /workspace/lila/conf/application.conf <<EOF
      net.site.name = "lila-gitpod"
      net.domain = "$(gp url 8080 | cut -c9-)"
      net.socket.domains = [ "$(gp url 8080 | cut -c9-)" ]
      net.base_url = "$(gp url 8080)"
      net.asset.base_url = "$(gp url 8080)"
      EOF
      ## Create config for lila-ws (websockets)
      tee /workspace/lila-ws-gitpod-application.conf <<EOF
      include "application"
      csrf.origin = "$(gp url 8080)"
      EOF
      ## Create config for fishnet clients
      tee /workspace/fishnet/fishnet.ini <<EOF
      [fishnet]
      cores=auto
      systembacklog=long
      userbacklog=short
      EOF
      ## Setup initial database and seed test data (users, games, puzzles, etc)
      mkdir -p /workspace/mongodb-data
      sudo mongod --fork --dbpath /workspace/mongodb-data --logpath /var/log/mongod.log
      mongo lichess /workspace/lila/bin/mongodb/indexes.js
      python3.9 /workspace/lila-db-seed/spamdb/spamdb.py --drop all
      redis-server --daemonize yes
      gp sync-done setup
      ## Compile js + css
      cd /workspace/lila && ./ui/build
      ## Switch editor to lila workspace
      open --reuse-window /workspace/lila

ports:
  - port: 8080
    name: lichess
    description: Your Lichess development site
  - port: 9663
    name: lila
    onOpen: ignore
  - port: 9664
    name: lila-ws
    onOpen: ignore
  - port: 9665
    name: lila-fishnet
  - port: 6379
    name: redis
    onOpen: ignore
  - port: 8212
    name: bloop
    onOpen: ignore
  - port: 27017
    name: mongodb
    onOpen: ignore
  - port: 8000
    name: docs
  - port: 587
    name: smtp
    onOpen: ignore
  - port: 8025
    name: mailhog

vscode:
  extensions:
    - scala-lang.scala
